version: '3'

services:

  # Service using an image directly
  direct-image-service:
    image: nginx:latest
    ports:
      - "8080:80"

  # Service using a Dockerfile in the dockerfile-copied-init folder
  service-with-copied-script:
    build:
      context: ./dockerfile-copied-init

  # Service using a Dockerfile in the dockerfile-mounted-init folder
  service-with-mounted-script:
    build:
      context: ./dockerfile-mounted-init
    volumes:
      - ./scripts:/usr/src/app/scripts
    entrypoint: /usr/src/app/scripts/init-script.sh
    command: echo "Command executed from docker-compose"
